### ISSUE TITLE
Consider introducing a mybinder.org link for the tutorials

### ISSUE THREAD

**Issue by BjoernLudwigPTB** [Met4FoF/agentMET4FOF#117]
This was not possible previously because of the heavy dependencies, but since those are gone, we could introduce on into the README.

**Comment by BjoernLudwigPTB** [comment]
Mybinder.org unfortunately does not work yet, because of the way we intend users to use the _requirements.txt_ and the _environment.yml_ files. Mybinder.org at the moment installs the dependencies from the _environment.yml_ and we expect developers to do the same. This ist not compatible with each other. Developers do not need or maybe even must not have the latest agentMET4FOF release installed into their environment, to avoid clashes or unwanted behaviour when using the installed version over the files in the filesystem. Mybinder.org needs agentMET4FOF installed to work with the tutorial notebooks. How should we go about this?

**Comment by BjoernLudwigPTB** [comment]
@anupam-prasad @bangxiangyong so guys, as promised  I request an opinion about our dependency management. Since as we state in the README we expect users anyway to install agentMET4FOF from PyPI.org via `pip install agentMET4FOF`. Following my understanding of these [official docs about `install_requires vs requirements files`](https://packaging.python.org/discussions/install-requires-vs-requirements/#install-requires-vs-requirements-files) I would suggest:

- use setup.py to specify our minimal dependencies under `install_requires` with minimal constraints (i.e. for `pip install agentMET4FOF` to be able to work with the agents),
- use setup.py to specify _ipykernel_ as optional dependency for the tutorials with minimal constraints (i.e. for `pip install angetMET4FOF[tutorials]` to be able to work with the tutorials as Jupyter Notebooks)
- compile all of these dependencies into a _requirements.txt_ containing specific version pinnings
- reference the _requirements.txt_  in the _environment.yml_ as currently (just update the Python version
- talking about the Python version... shall we switch to Python 3.8 as default?! Version pinning requires obviously to choose one Python version, which we then would mention in the README. 
Either that or more complex specify specific version pinnings for different Python versions as we do with PyDynamic.

So, please give me an opinion if you are fine with the suggestions or if you spot any inconveniences or have any obligations.

**Comment by anupam-prasad** [comment]
I'm onboard with the first four points.

My only question is that since PyDynamic will be integrated into the tutorials in the future, should it also be included as an optional dependency? I'm not sure what effect this would have on the version pinning.

**Comment by BjoernLudwigPTB** [comment]
> I'm onboard with the first four points.
> 
> My only question is that since PyDynamic will be integrated into the tutorials in the future, should it also be included as an optional dependency? I'm not sure what effect this would have on the version pinning.

This would just introduce another pinned version of PyDynamic into the requirements.txt and a mention of PyDynamic in the _extras_require_-_[tutorial]_-section. As soon as Xiang has expressed his thoughts I could start to prepare the corresponding changes.

**Comment by BjoernLudwigPTB** [comment]
Those changes actually have been applied long ago and still we will close this issue now without the mybinder link. The main reason is, that running the agents on mybinder does not allow to visit the dashboard. Instead we might look for an option to run the docker container somewhere. But still, this here should be closed for good now.
