### ISSUE TITLE
Integrating time-series-buffer and AgentBuffer

### ISSUE THREAD

**Issue by bangxiangyong** [Met4FoF/agentMET4FOF#129]
Since the implementation of AgentBuffer as part of every agent now, we should think of a way for enabling metrological buffering and suggest that:
- Extend a class MetrologicalAgentBuffer which adds constraints on the data with uncertainties attached and metadata
- utilise time-series-buffer as part of it
- rework tutorial 4 to be consistent with these changes above

**Comment by BjoernLudwigPTB** [comment]
After merging #179 we noticed this in the output while running _agentMET4FOF_tutorials/buffering/metrological_buffering.py_:

```shell
[2021-04-23 11:42:07.578287] (SineGenerator): Sending: [array([[nan,  0., nan,  0.],
       [nan,  0., nan,  0.],
       [nan,  0., nan,  0.],
       [nan,  0., nan,  0.],
       [nan,  0., nan,  0.]]), <time_series_metadata.scheme.MetaData object at 0x7ff534a631c0>]
```
and observe an empty plot in the corresponding dashboard. We should resolve this and introduce a test, checking for expected output via the monitor agent.

**Comment by bangxiangyong** [comment]
Should be resolved with https://github.com/Met4FoF/agentMET4FOF/commit/bbc1ae925d221fdd79715a46e48c91059b2d4cd6
