### ISSUE TITLE
Improve README regarding the required commands and explanations

### ISSUE THREAD

**Issue by BjoernLudwigPTB** [Met4FoF/agentMET4FOF#157]
We want to simplify the README further. Along with that we want to provide useful information to other project partners (like [GEMIMEG II](https://www.digitale-technologien.de/DT/Navigation/DE/ProgrammeProjekte/AktuelleStrategischeEinzelprojekte/gemimeg2/gemimeg2.html)) and develop an agentMET4FOF landing page on the project page.

**Comment by BjoernLudwigPTB** [comment]
This repository is a good example: https://github.com/online-ml/river

At the moment we have the following locations of project presentation:

- the [README](README.md)
- the [docs](https://agentmet4fof.readthedocs.io/en/latest/?badge=latest)

We need to change/adapt:

- [ ] authors are mentioned in the docs, which we need to update and specifically add PTB authors (Max, Anupam, Björn) @BjoernLudwigPTB 
- [ ] the copyright @BjoernLudwigPTB 
- [ ] the _About_ section in the README @bangxiangyong 
- [ ] choose a tutorial with an interesting initial output and replace the screenshot in the README @bangxiangyong 
- [ ] we should add a features list linking to specific parts of our documentation or the code or tutorials @bangxiangyong @anupam-prasad

**Comment by BjoernLudwigPTB** [comment]
We could/should take a part of Xiang's publication to describe what the software actually is doing.

**Comment by BjoernLudwigPTB** [comment]
@anupam-prasad @bangxiangyong @mgrub I suggest taking a major part of our abstract for the SMSI 2020 conference's contribution to motivate agentMET4FOF in the README's about section:

> Sensor deployments in industrial applications usually form networks in all sorts of environments. This requires a flexible framework for the implementation of the corresponding data analysis. An excellent way to represent such networks is a multi-agent system (MAS), where independent software modules (agents) encapsulate properties and functionalities. _agentMET4FOF_ is an interactive and flexible open-source implementation of such a MAS, developed in the European metrology research project EMPIR 17IND12 Met4FoF. The software engineering process is driven by several industry-oriented use cases with the aim of impacting on IIoT applications. This leads to a framework that is specialized in representing heterogeneous sensor networks.

**Comment by anupam-prasad** [comment]
This looks good. Is there a German version? I'll translate it otherwise.

**Comment by BjoernLudwigPTB** [comment]
> This looks good. Is there a German version? I'll translate it otherwise.

No, I do not think there is a German version yet.

**Comment by BjoernLudwigPTB** [comment]
I included the abstract and tweaked the headings around it as well as mixed in the former text. See #158 .

**Comment by BjoernLudwigPTB** [comment]
I closed the ToDo list and transferred the missing points to the related PR #158 . Let's continue there.
