### ISSUE TITLE
Check if we really want to different variables to take the controller agent in a network for the different backends

### ISSUE THREAD

**Issue by BjoernLudwigPTB** [Met4FoF/agentMET4FOF#168]
[In the Mesa backend the attribute holding the network controller agent is `self._controller`](https://github.com/bangxiangyong/agentMET4FOF/blob/24932b8605647a2bcc38d82d80a15da20bf50bf0/agentMET4FOF/agents.py#L1227) and[ for the osBrain network it is `self.controller`](https://github.com/bangxiangyong/agentMET4FOF/blob/24932b8605647a2bcc38d82d80a15da20bf50bf0/agentMET4FOF/agents.py#L1215). Especially the [`_get_controller()`](https://github.com/bangxiangyong/agentMET4FOF/blob/24932b8605647a2bcc38d82d80a15da20bf50bf0/agentMET4FOF/agents.py#L1397) method suggests a bug here. Although this seems very minor, because in case for the _osBrain_ backend there is not self._controller we simply define it. Although in most(/all?) cases that would be not needed, if we straightaway would use `self._controller`. Besides the `self.controller` is not used anywhere outside the `start_server_osbrain`.

@bangxiangyong Is this correct?

**Comment by bangxiangyong** [comment]
yes, you are right we'll need a consistent and clearer way for it
