### ISSUE TITLE
Add a features list to the README

### ISSUE THREAD

**Issue by BjoernLudwigPTB** [Met4FoF/agentMET4FOF#182]
We should add a features list linking to specific parts of our documentation or the code or tutorials.

**Comment by BjoernLudwigPTB** [comment]
I put down my thoughts: https://github.com/Met4FoF/agentMET4FOF#features.

@bangxiangyong Could you check once more, if you agree, please?

@anupam-prasad Now it's your turn! :rocket:

**Comment by anupam-prasad** [comment]
I made a few minor changes. I think we could also mention that there are generic agents available that
can be used as starting points in simulations.

It looks good otherwise.

**Comment by BjoernLudwigPTB** [comment]
@anupam-prasad I have one remark on one of your changes: https://github.com/Met4FoF/agentMET4FOF/commit/06d27b54fc85f6267be728ebfaefc92617c94054#r53537383

**Comment by BjoernLudwigPTB** [comment]
> [...] I think we could also mention that there are generic agents available that
> can be used as starting points in simulations.

@anupam-prasad You are absolutely right. Dare to insert a first draft?

**Comment by anupam-prasad** [comment]
> > [...] I think we could also mention that there are generic agents available that
> > can be used as starting points in simulations.
> 
> @anupam-prasad You are absolutely right. Dare to insert a first draft?

Hi. Sorry I just replied to this. It completely slipped my mind. I'll add a few lines soon.
