### ISSUE TITLE
Dashboard not restarting cleanly

### ISSUE THREAD

**Issue by bangxiangyong** [Met4FoF/agentMET4FOF#186]
I'm using pycharm 2020.2 and Windows OS with following steps:
1. Start an agent network (e.g run tutorial 1)
2. Open dashboard on web
3. Stop the python script 
4. Repeat step 1 i.e restart an agent network

However, I was unable to launch the dashboard and it shows :
`Dashboard or something else is running on: 127.0.0.1:8050. ....`

Upon inspection, i find commenting these lines of code to completely fix the problem above:
https://github.com/Met4FoF/agentMET4FOF/blob/develop/agentMET4FOF/dashboard/Dashboard.py
```
            for connection in psutil.net_connections():
                if connection.laddr.port == _port and connection.laddr.ip == ip_addr:
                    return False
```

OR, wait a long while and run step 1 again and it works. 

Not sure if it is a Windows only thing, for some reason the port 8050 is not terminating immediately and it takes some time for the dashboard to cleanly close at port 8050.

**Comment by BjoernLudwigPTB** [comment]
It takes about a minute, right? This is due to some convention on how long a previously opened TCP connection port should be waiting for still incoming messages to that port. I could not find a way, to properly avoid that on shutting down the networks. I am a little surprised though, that you were able to simply comment this out and properly restart the Dashboard. Could you try out, if this works from the command line as well?

**Comment by BjoernLudwigPTB** [comment]
Do you already have a branch with the proposed changes?

**Comment by bangxiangyong** [comment]
Nope, i dont have a branch with those changes yet. I was trying to get your opinion/validation because the change i'm likely to propose is actually removing those 3 lines of codes (above).  im not sure whether may lead to any issues?

**Comment by BjoernLudwigPTB** [comment]
This is the problem: https://app.circleci.com/pipelines/github/Met4FoF/agentMET4FOF/634/workflows/6f351962-e973-4c5a-9c61-5e27c18ab6c1/jobs/1199

It happens every once in a while in when running the pipeline. We should really find a way of cleanly shutting down the dashboard from within the code, wihtout the need to have users use PyCharm to terminate the processes via the IDE stop button.

**Comment by BjoernLudwigPTB** [comment]
> It takes about a minute, right? This is due to some convention on how long a previously opened TCP connection port should be waiting for still incoming messages to that port. I could not find a way, to properly avoid that on shutting down the networks. I am a little surprised though, that you were able to simply comment this out and properly restart the Dashboard. Could you try out, if this works from the command line as well?

@bangxiangyong Could you try out and tell us if it works from the command line. We get errors in our pipeline since you took out the additional check almost on every run.

**Comment by bangxiangyong** [comment]
Yes you are right. i just tried on the console, its not terminating and the next console execution gives `Dashboard or something else is running on: 127.0.0.1:8050.` But, if using the pycharm Run, it works nicely.

however with the lines of code added above, there's still that problem above where it doesnt close immediately and takes about a minute to close ?

this is troubling, we should put this on highest priority to fix..
