### ISSUE TITLE
Introduce a test showing the need for multiprocess.context.Process

### ISSUE THREAD

**Issue by BjoernLudwigPTB** [Met4FoF/agentMET4FOF#189]
We now switched back to `multiprocess.Process` (which we [import from pathos.helpers](https://github.com/Met4FoF/agentMET4FOF/blob/e4dbbf91abc39b89f56971526cc3bba758d2af33/agentMET4FOF/dashboard/Dashboard.py#L167). I remember [we had that before](https://github.com/Met4FoF/agentMET4FOF/commit/e9c83827f0b3e18bbabe28fc08cf58b0f2d699f6) and [could not tell later, why we used `multiprocess`](https://github.com/Met4FoF/agentMET4FOF/issues/58). We should add a test which fails for multiprocessing, but does not for multiprocess and replace the pathos import by the direct import of `multiprocess.Process` in case we do not need anything else from pathos.

@bangxiangyong Is there a reason why you did not choose to use `multiprocess.Process` over `pathos.helpers.mp.Process` which is basically [an alias for the `multiprocess` class](https://github.com/uqfoundation/pathos/blob/7106d15440a868d0ecf242286d255a39f28b3e77/pathos/helpers/__init__.py#L14)?

**Comment by bangxiangyong** [comment]
Yes, the main problem is in `multiprocess.context.Process` which attempts to `pickle` the parameters which include modules which are unpicklable. Importing `pathos.helpers.mp.Process` actually causes it to use `dill` which is able to serialise the modules instead of `pickle` and is not exactly the same as `multiprocess.context.Process`.

**Comment by bangxiangyong** [comment]
In my earlier runs, i faced a pickling error of the module `Dashboard_agt_net` in https://github.com/Met4FoF/agentMET4FOF/blob/develop/agentMET4FOF/agents.py

```
            dashboard_params = {
                "dashboard_modules": dashboard_modules,
                "dashboard_layouts": [Dashboard_agt_net] + dashboard_extensions,
                "dashboard_update_interval": dashboard_update_interval,
                "max_monitors": dashboard_max_monitors,
                "ip_addr": ip_addr,
                "port": dashboard_port,
                "agentNetwork": self,
            }

            # Initialize dashboard process/thread.
            if self.backend == "osbrain":
                from .dashboard.Dashboard import AgentDashboardProcess

                self.dashboard_proc = AgentDashboardProcess(**dashboard_params)
```
I'm not sure if the test suite caught that ?..

**Comment by BjoernLudwigPTB** [comment]
We should write a test which [monkeypatches](https://docs.pytest.org/en/stable/monkeypatch.html) _multiprocess.context.Process_ with the in-built _multiprocessing.Process_ and call that in a [`with pytest.raises`](https://docs.pytest.org/en/stable/assert.html#assertions-about-expected-exceptions) clause. As of now, this is not covered and actually never was, since there were no errors when we switched to _multiprocessing.Process_.

**Comment by BjoernLudwigPTB** [comment]
> Yes, the main problem is in `multiprocess.context.Process` which attempts to `pickle` the parameters which include modules which are unpicklable. Importing `pathos.helpers.mp.Process` actually causes it to use `dill` which is able to serialise the modules instead of `pickle` and is not exactly the same as `multiprocess.context.Process`.

Are you sure, that this is true for `multiprocess.context.Process`not only `multiprocessing.Process`. It looks to me as if we are simply reimporting the import of `pathos` form `multiprocess`. (see https://github.com/uqfoundation/pathos/blob/67c714b4052ebd5b91a21ef55bb1d18fad8727ab/pathos/helpers/__init__.py#L14 where our import path's `mp` is defined as `multiprocess`). Multiprocess is the package from the guys who are writing _pathos_ saying, it allows for [improved serialization using `dill`](https://github.com/uqfoundation/multiprocess#major-changes).

**Comment by BjoernLudwigPTB** [comment]
Today we discussed and agreed that the exchange of `pathos` with `multiprocess` probably is very reasonable. @BjoernLudwigPTB confirmed the expected behaviour in Linux. @bangxiangyong will now confirm expected behaviour on Windows and then #204 gets merged.
