### ISSUE TITLE
Integration with OPC-UA

### ISSUE THREAD

**Issue by bangxiangyong** [Met4FoF/agentMET4FOF#19]
Will need to investigate whether which option is better and feasible: 

1. Replacing underlying communication of Pyro4 with OPC-UA
2. Providing an external interface to OPC-UA

**Comment by BjoernLudwigPTB** [comment]
@BeSeeTek This is something we would love to discuss with you, since you have much more insight what the implications would be regarding:
1.  implementation effort,
1.  benefit.

**Comment by BjoernLudwigPTB** [comment]
>     1. Replacing underlying communication of Pyro4 with OPC-UA
> 
>     2. Providing an external interface to OPC-UA
By the way: Does option one automatically include the agents' public interface to be OPC-UA compliant? At a second glance, it appears to me that we still would have to separately design the OPC-UA capability of the agents to the outside world with underlying OPC-UA mechanisms (i.e. without Pyro4 under the hood).

**Comment by bangxiangyong** [comment]
For option one, I was thinking that OPC-UA clients will be able to view and connect to the agents (which are viewed as OPC-UA servers/clients themselves). Depending on how it turns out, it might still require external interface to OPC-UA or may not (the agents commands might be already be compatible to connect to OPC-UA).

Nevertheless, after discussion with @BeSeeTek, it appears that the second option is recommended due to the work required, and is still OPC-UA compliant at the end of the day.

**Comment by BjoernLudwigPTB** [comment]
Maybe it would be a good idea to start with an external interface which somehow internally can be connected to agents or vice-versa and from there, at a later point, go to integrate this external interface into the agents.

**Comment by BjoernLudwigPTB** [comment]
As far as I can see, there is no use case for this anymore. I will close this issue for now, but feel free to open it up again, once you have a need for that!
