### ISSUE TITLE
Incorporate valuable changes from VSL's code

### ISSUE THREAD

**Issue by BjoernLudwigPTB** [Met4FoF/agentMET4FOF#194]
Gertjan provided a draft for improvements regarding his tasks [here](https://github.com/gertjan123/Met4FoF-redundancy). Lets review his changes and take everything that is useful for us especially from his [metrological_streams_v2.py](https://github.com/gertjan123/Met4FoF-redundancy/blob/master/Met4FoF_redundancy/agentMFred/metrological_streams_v2.py ).

**Comment by bangxiangyong** [comment]
Are there hints as to what were the required methods and current limitation which motivated Gertjan to create a `v2` ?

**Comment by anupam-prasad** [comment]
#211 #198

**Comment by BjoernLudwigPTB** [comment]
We should have another discussion about if not and how to integrate the actual redundancy treatment from the [RedundancyAgent](https://github.com/gertjan123/Met4FoF-redundancy/blob/c414f57ce2b54b0a115131bfa59361e505a76b73/Met4FoF_redundancy/agentMFred/redundancyAgents1.py#L55).
