### ISSUE TITLE
Support ZeMA's effort to integrate their machine learning with agentMET4FOF

### ISSUE THREAD

**Issue by BjoernLudwigPTB** [Met4FoF/agentMET4FOF#20]
ZeMA (@TanjaDorst) should use *agentMET4FOF* together with their machine learning methods with uncertainties and we should support their efforts (e.g. refactor interfaces if this could encourage others to work with *agentMET4FOF* or integrate required functions)

**Comment by BjoernLudwigPTB** [comment]
Next:
1. talk to Tanja about the current state of her work and try to find out, if we can use part of it with the agents,
1. check how we can use Ehlimanas work with the agents.

**Comment by bangxiangyong** [comment]
Tanja's current work of adding time synchronization noise can be packed into an agent and as part of the "pipeline" in #17

**Comment by BjoernLudwigPTB** [comment]
Since Tanja practically finished her work on the project, this is ready to be closed. The ZeMA pipeline was implemented as a use case long ago as well: https://github.com/Met4FoF/agentMET4FOF_ZeMA_emc. Thanks for the great work!
