### ISSUE TITLE
amplitude vs. value

### ISSUE THREAD

**Issue by gertjan123** [Met4FoF/agentMET4FOF#236]
Minor variable name issue:

I would rather call the output of a sine function 'value'. The 'amplitude' is something different.

y = A * sin(2*pi*f*t + phi_ini).

A ... amplitude
y ... value

**Comment by BjoernLudwigPTB** [comment]
You are right! We should change that, I think.

@anupam-prasad @bangxiangyong what are your thoughts? I suggest to include this and resolve it in the next sprint.

**Comment by anupam-prasad** [comment]
I agree with Gertjan here. Amplitude usually refers to a multiplicative factor.

**Comment by BjoernLudwigPTB** [comment]
> I agree with Gertjan here. Amplitude usually refers to a multiplicative factor.
> 
> Edit: It might also be useful to add an `amplitude` variable that lets us define signals with an amplitude other than 1.

I totally agree. The original issue I would actually not consider an issue, since the variable `amplitude` is just local and can simply refactored any time, by anyone without any effect. Still we should do it soon, and  open another issue to introduce an amplitude parameter for the [SineGenerator](https://github.com/Met4FoF/agentMET4FOF/blob/5246065848c03bb4df9842d19a20d8247c01ebd3/agentMET4FOF/streams.py#L372) and [CosineGenerator](https://github.com/Met4FoF/agentMET4FOF/blob/5246065848c03bb4df9842d19a20d8247c01ebd3/agentMET4FOF/streams.py#L399) classes.

**Comment by gertjan123** [comment]
"The original issue I would actually not consider an issue"
Is it nevertheless fine that I use this Github issue tool for communicating my thoughts?

**Comment by gertjan123** [comment]
"Edit: It might also be useful to add an amplitude variable that lets us define signals with an amplitude other than 1."

A parameter for an 'initial phase' would also be good then. Like the MultiWaveGenerator.

**Comment by gertjan123** [comment]
I guess I can close this issue, as a new issue was opened.

**Comment by BjoernLudwigPTB** [comment]
> I guess I can close this issue, as a new issue was opened.

Still, the refactoring should be done. If you like, simply choose another name or drop the unneeded local variable and simply return the computation. That's your chance to become contributor of `agentMET4FOF`. :wink:

**Comment by gertjan123** [comment]
I saw I'm too late already...
Next time!

**Comment by BjoernLudwigPTB** [comment]
> I saw I'm too late already...
> Next time!

Well, not really, since the new issue #239 refers to the new parameter, but not to the renaming or dropping of the private amplitude variable. Or did I miss anything?

**Comment by gertjan123** [comment]
Anupam did the renaming already 5 days ago, I think. 
#239 is indeed something else, more involved.

**Comment by BjoernLudwigPTB** [comment]
> Anupam did the renaming already 5 days ago, I think.
> #239 is indeed something else, more involved.

Thanks for pointing me to it! :+1:
