### ISSUE TITLE
Provide key facts for the new project homepage in bullet point style

### ISSUE THREAD

**Issue by BjoernLudwigPTB** [Met4FoF/agentMET4FOF#253]
@BjoernLudwigPTB [kickstarts](https://github.com/Met4FoF/agentMET4FOF/issues/253#issuecomment-880837244) this and then [@bangxiangyong takes over](https://github.com/Met4FoF/agentMET4FOF/issues/253#issuecomment-880838791).

**Comment by BjoernLudwigPTB** [comment]
Kickstarter for agentMET4FOF key facts:

- [FOSS project](https://github.com/Met4FoF/agentMET4FOF#coming-soon)
- allows to
  - quickly set up and run a [metrologically enabled multi-agent system](https://github.com/Met4FoF/agentMET4FOF#about)
  - handle both [static data sets and online data streams](https://agentmet4fof.readthedocs.io/en/latest/agentMET4FOF_streams.html#module-agentMET4FOF.streams.base_streams)
  - [consider measurement uncertainties as well as metadata with the provided message system](https://agentmet4fof.readthedocs.io/en/latest/agentMET4FOF_tutorials/tutorial_7_generic_metrological_agent.html)
- comes bundled with [many tutorials](https://github.com/Met4FoF/agentMET4FOF/tree/develop/agentMET4FOF_tutorials)
- accompanied by [several use cases](https://github.com/Met4FoF?q=agentMET4FOF&type=&language=&sort=) with close-to-industry IIoT applications
- comprehensive and ever growing [documentation](https://agentmet4fof.readthedocs.io/)

**Comment by BjoernLudwigPTB** [comment]
@bangxiangyong That's it for a kickstarter. The target group are working group leaders, researchers, department heads in industry for whom the use of our application could be interesting. Do you think, you can build on that?

**Comment by BjoernLudwigPTB** [comment]
@anupam-prasad Your more than welcome to comment on the draft as well, of course!

**Comment by bangxiangyong** [comment]
Yes, that looks great for a start .. !

**Comment by anupam-prasad** [comment]
> @anupam-prasad Your more than welcome to comment on the draft as well, of course!

Looks fine to me as well!
