### ISSUE TITLE
Consider changing server listening on localhost i.e. 127.0.0.1 to listening on all interfaces i.e. 0.0.0.0

### ISSUE THREAD

**Issue by BjoernLudwigPTB** [Met4FoF/agentMET4FOF#254]
We assume, that the default server setting of host="localhost" is the reason for us not being able to run the agents inside a container. We could change that, o a development release and see, if that solves the issue. The release could be deleted later if it does not work.

**Comment by BjoernLudwigPTB** [comment]
It actually works! So we now probably know as well, why we previously were not able to deploy the agents in a container. We will further investigate this from tomorrow.

**Comment by BjoernLudwigPTB** [comment]
We know, yes! I am able to serve the agents dashboard from inside a docker container to a host machine with this setting.

@bangxiangyong Do you have any objections to changing the default IP? It is important to know that 0.0.0.0 refers to all interfaces, so you can still visit 127.0.0.1 or 'localhost' in the browser, if that was possible before.

**Comment by BjoernLudwigPTB** [comment]
With the merge of #257 into #215 , this is almost closed.

**Comment by bangxiangyong** [comment]
Good to hear that it works on the docker, i have no objections as of now ..
