### ISSUE TITLE
Contact the D-SI team to get more details about how we can use it

### ISSUE THREAD

**Issue by BjoernLudwigPTB** [Met4FoF/agentMET4FOF#28]
This leads to a more detailed description of #22.

**Comment by BjoernLudwigPTB** [comment]
I got in touch with the colleagues and now wait for a response.

**Comment by BjoernLudwigPTB** [comment]
@bangxiangyong What do you think on how far do we go in this sprint? I now have got quite some bits of documentation and information about D-SI. Is this all we needed in this sprint or shall I dive into it already?

**Comment by bangxiangyong** [comment]
@BjoernLudwigPTB ideally would be good if you can look into it first, and suggest actions for next sprint. i'm briefly looking at it too.
