### ISSUE TITLE
This site can’t be reached127.0.0.1 refused to connect.

### ISSUE THREAD

**Issue by ITdeveloper2020** [Met4FoF/agentMET4FOF#297]
After excuting:

```
>>> from agentMET4FOF_tutorials.tutorial_1_generator_agent import demonstrate_generator_agent_use
>>> generator_agent_network = demonstrate_generator_agent_use()
```
Then open the http://127.0.0.1:8050/ on the browser, I get :
```
This site can’t be reached127.0.0.1 refused to connect.
```
I used Jupyter, vs code and colabstill have the same result, 
Can you help with this issue please? thank you.

**Comment by BjoernLudwigPTB** [comment]
That's strange. Please let us know, which operating system you are on and share the console output after `generator_agent_network = demonstrate_generator_agent_use()` of the shell, in which you invoked your python interperter .

**Comment by ITdeveloper2020** [comment]
I'm using windows 11, this is when I use colab
after excuting generator_agent_network = demonstrate_generator_agent_use()
Starting NameServer...
Broadcast server running on 0.0.0.0:9091
NS running on 127.0.0.1:3333 (127.0.0.1)
URI = PYRO:Pyro.NameServer@127.0.0.1:3333

--------------------------------------------------------------
|                                                            |
| Your agent network is starting up. Open your browser and   |
| visit the agentMET4FOF dashboard on http://127.0.0.1:8050/ |
|                                                            |
--------------------------------------------------------------

INFO [2022-11-08 09:20:03.680317] (SineGeneratorAgent_1): INITIALIZED
INFO [2022-11-08 09:20:03.727089] (MonitorAgent_1): INITIALIZED
[2022-11-08 09:20:03.753925] (SineGeneratorAgent_1): Connected output module: MonitorAgent_1
SET STATE:   Running

but when I open http://127.0.0.1:8050/ on the browser I got 
This site can’t be reached127.0.0.1 refused to connect.
Try:

Checking the connection
[Checking the proxy and the firewall](chrome-error://chromewebdata/#buttons)
ERR_CONNECTION_REFUSED

**Comment by BjoernLudwigPTB** [comment]
Please, when posting here on GitHub, format your code or console outputs with backticks "`"or using the respective buttons. That makes it much easier to read.

You should definitely check proxy and firewall settings as already suggested by your browser. Are you in an environment, where you need a proxy to connect to the internet or do you have a firewall active, that might interfere with your connections?

Is there any output after `SET STATE:   Running`? Did you install the package locally or do you use Docker to start the network?

**Comment by ITdeveloper2020** [comment]
Sorry, I didn't post issues before on GitHub.
I did check proxy and firewall both disabled, and install the pachage locally on two devices still gave me the same result.
"Is there any output after SET STATE: Running" no output after it.

**Comment by BjoernLudwigPTB** [comment]
Could you please give a try to start a Mesa backend network with
```
>>> from agentMET4FOF_tutorials.tutorial_6_mesa_backend import demonstrate_mesa_backend
>>> mesa_network = demonstrate_mesa_backend()
```
If that works, we know, that something is wrong with the osBrain mechanisms.

**Comment by ITdeveloper2020** [comment]
I did, still give my the same result sorry, no I don't plan to set up a distributed network.

**Comment by BjoernLudwigPTB** [comment]
Please check in the PowerShell (PS), if after starting the network (of either of the tutorials), the port is opened. Execute in the PS:

```powershell
netstat | findstr "127.0.0.1:8080"
```

The command might run for some time without output, that's okay. If it returns to the shell without showing a line containing the address `127.0.0.1:8080` the agent server is not even running. If the address appears, there is something going wrong with you connecting to it. Have you tried different browsers? If not do that. If it does not work with Google Chrome, you might try the solution showed at 3:40 in this video: https://www.youtube.com/watch?v=fzTq0e-tHvo&t=3m40s.

**Comment by ITdeveloper2020** [comment]
this output for:
">>> from agentMET4FOF_tutorials.tutorial_6_mesa_backend import demonstrate_mesa_backend
>>> mesa_network = demonstrate_mesa_backend()"
"--------------------------------------------------------------
|                                                            |
| Your agent network is starting up. Open your browser and   |
| visit the agentMET4FOF dashboard on http://127.0.0.1:8050/ |
|                                                            |
--------------------------------------------------------------

[2022-11-09 10:11:47.513927] (SineGeneratorAgent_1): INITIALIZED
[2022-11-09 10:11:47.514188] (MonitorAgent_1): INITIALIZED
[2022-11-09 10:11:47.514253] (SineGeneratorAgent_1): Connected output module: MonitorAgent_1
SET STATE:   Running
/usr/local/lib/python3.7/dist-packages/agentMET4FOF/dashboard/Dashboard_agt_net.py:4: UserWarning:


The dash_core_components package is deprecated. Please replace
`import dash_core_components as dcc` with `from dash import dcc`

/usr/local/lib/python3.7/dist-packages/agentMET4FOF/dashboard/Dashboard_agt_net.py:6: UserWarning:


The dash_html_components package is deprecated. Please replace
`import dash_html_components as html` with `from dash import html`

/usr/local/lib/python3.7/dist-packages/agentMET4FOF/dashboard/LayoutHelper.py:2: UserWarning:


The dash_table package is deprecated. Please replace
`import dash_table` with `from dash import dash_table`

Also, if you're using any of the table format helpers (e.g. Group), replace 
`from dash_table.Format import Group` with 
`from dash.dash_table.Format import Group`

[2022-11-09 10:11:47.590191] (SineGeneratorAgent_1): Pack time: 1.4e-05
[2022-11-09 10:11:47.597167] (SineGeneratorAgent_1): Sending: [0.]
[2022-11-09 10:11:47.597381] (MonitorAgent_1): Received: {'from': 'SineGeneratorAgent_1', 'data': array([0.]), 'senderType': 'SineGeneratorAgent', 'channel': 'default'}
[2022-11-09 10:11:47.597569] (MonitorAgent_1): Buffer: {'SineGeneratorAgent_1': array([0.])}
[2022-11-09 10:11:47.597628] (MonitorAgent_1): Tproc: 0.00019
[2022-11-09 10:11:47.701257] (SineGeneratorAgent_1): Pack time: 1.3e-05
[2022-11-09 10:11:47.702610] (SineGeneratorAgent_1): Sending: [0.06279052]
[2022-11-09 10:11:47.702856] (MonitorAgent_1): Received: {'from': 'SineGeneratorAgent_1', 'data': array([0.06279052]), 'senderType': 'SineGeneratorAgent', 'channel': 'default'}
[2022-11-09 10:11:47.703138] (MonitorAgent_1): Buffer: {'SineGeneratorAgent_1': array([0.        , 0.06279052])}
[2022-11-09 10:11:47.703203] (MonitorAgent_1): Tproc: 0.000289"

**Comment by BjoernLudwigPTB** [comment]
It appears you are using Python 3.7, but agentMET4FOF is intended to be used with Python 3.8 or higher, although I am not convinced, that is the reason of your problems. Please try to use a more recent Python interpreter. Did you already run the PowerShell command:

```
netstat | findstr "127.0.0.1:8050"
```
or the [fix from the video as I asked above](https://github.com/Met4FoF/agentMET4FOF/issues/297#issuecomment-1308482645)?

**Comment by BjoernLudwigPTB** [comment]
> "/usr/local/lib/python3.7/dist-packages/agentMET4FOF/dashboard/Dashboard_agt_net.py:4: UserWarning:

This user warning is no problem altough it indicates, that you are not working with the most recent version of the agents. Please as already asked above: install a more recent version of Python (if not already done), reinstall agentMET4FOF, and then try [the other solutions](https://github.com/Met4FoF/agentMET4FOF/issues/297#issuecomment-1308722354).

**Comment by ITdeveloper2020** [comment]
The solution which fixes this issue is to make sure you are using python 3.7.

**Comment by BjoernLudwigPTB** [comment]
> The solution which fixes this issue is to make sure you are using python 3.7.

Thanks for commenting about your solution! Are you sure, you are using Python 3.7? In fact the most recent versions of the agents are [supposed to run with Python 3.8 or newer](https://github.com/Met4FoF/agentMET4FOF/blob/20da36d503dac1d8e5cc16998f3c7e3e13bda179/setup.py#L77). I will include a hint about that in the README and the docs as I just noticed, that we do not mention that anymore.

**Comment by BjoernLudwigPTB** [comment]
Closing as of now, as the issue seems to be fixed.
