### ISSUE TITLE
Incorrect docstring init_agent

### ISSUE THREAD

**Issue by bangxiangyong** [Met4FoF/agentMET4FOF#307]
The docstring of `init_agent` in [base_agents.py](https://github.com/Met4FoF/agentMET4FOF/blob/develop/agentMET4FOF/agents/base_agents.py) says `Calls user-defined 'init_parameters()' upon finishing.` However, this isn't the case as shown in lines 233-234 and 251-252 of [network.py](https://github.com/Met4FoF/agentMET4FOF/blob/develop/agentMET4FOF/network.py) where it is the other way round: `init_parameters` is called first, followed by `init_agent`.

**Comment by BjoernLudwigPTB** [comment]
Especially, no call of `init_parameters()` is oart of `init_agent()` which is good, as the logic behind those methods does not overlap. I think, we should simply remove this statement from the docstring. Do you think, that would be appropriate @bangxiangyong ?

**Comment by bangxiangyong** [comment]
Well, actually i was fiddling with the `buffer_size` parameter in `init_agent()` and wanted to instantiate it via `init_parameters()` instead. and was somewhat confused by the results which didn't tally: the `init_agent()` then overrides the buffer size despite what i did with the buffer size in `init_parameters()`. 

We could either remove it (which is an incorrect statement), or actually make it clearer, just in case there would be interest similar to what i went through. There could be other better ways perhaps

**Comment by BjoernLudwigPTB** [comment]
I'd say, the clarification should actually be made somewhere more visible. `init_agent()` is somewhat downstream and should not be thought about in general usage scenarios. The usual choice of `buffer_size` can be made during the initialization of the instance as is shown in the [buffering tutorial](https://github.com/Met4FoF/agentMET4FOF/blob/develop/agentMET4FOF_tutorials/buffering/basic_buffering.py#L80). If one wanted to change the parameter, it should be done via calling `init_parameters()` where it then should be described and in fact taken care of an optional parameter. In (maybe all) our examples and implementations I can't find a parameter `buffer_size`. There actually already is an open issue #224 about unexpected behaviour of the parameter `buffer_size`.
